version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  # sqlite3:
  #   image: nouchka/sqlite3:latest
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./db/:/root/db/